server:
  port: 9003
  
#Registering the application instance in the Euraka server
eureka:         
    client:
      service-url:
        defaultZone: http://localhost:9000/eureka/
        
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #Route Mapping
      - id: loginMicroservice               #RouteIdentifier
        uri: http://localhost:9001/        #Respective microservice URL which needs to be mapped
        #uri: 
         # lb://LOGIN-SERVICE                #Respective dynamic microservice URL which needs to be mapped
        #Request Context Path Mapping
        predicates:
        - Path=/login-service/**          
        
        #Route Mapping - With out Filters - Version 2 Request
      - id: cartMicroservice
        uri: http://localhost:9002/
        predicates:
        - Path=/cart-serv/**

        #Route Mapping - With Filters - Version 1 Request
      #- id: cartMicroservice
       # uri: http://localhost:9002/
        #predicates:
       # - Path=/cart-service/** 
       # filters:
       # - RewritePath=/cart-service, /cart-serviceV2/      #Rewriting the path 
        
        # PreFilter - AddRequestHeader=custom-Request-header, customer-Request-header-value
        # PostFilter - AddResponseHeader=custom-Request-header, customer-Response-header-value
       

